name: (Staging) CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment (Preview)
        run: vercel pull --yes --environment=preview --git-branch=main --token=${{ secrets.VITE_VERCEL_TOKEN }}

      - name: Build project for Cypress
        run: npm run build
        env:
          VITE_AZURE_CLIENT_ID: ${{ secrets.VITE_AZURE_CLIENT_ID }}
          VITE_AZURE_TENANT_NAME: ${{ secrets.VITE_AZURE_TENANT_NAME }}
          VITE_AZURE_USER_FLOW: ${{ secrets.VITE_AZURE_USER_FLOW }}
          VITE_AZURE_REDIRECT_URI: ${{ secrets.VITE_AZURE_REDIRECT_URI }}
          VITE_APP_URL: ${{ secrets.VITE_APP_URL }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
          VITE_DEFAULT_LOCALE: ${{ secrets.VITE_DEFAULT_LOCALE }}
          VITE_FALLBACK_LOCALE: ${{ secrets.VITE_FALLBACK_LOCALE }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      # - name: Start project locally
      #   run: npm run preview &

      # - name: Wait for local server
      #   uses: jakejarvis/wait-action@v0.1.1
      #   with:
      #     url: http://localhost:4173
      #     timeout: 60

      # - name: Cypress run
      #   uses: cypress-io/github-action@v3
      #   with:
      #     record: true
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.VITE_CYPRESS_RECORD_KEY }}
      #     CYPRESS_AZURE_AD_B2C_EMAIL: ${{ secrets.CYPRESS_AZURE_AD_B2C_EMAIL }}
      #     CYPRESS_AZURE_AD_B2C_PASSWORD: ${{ secrets.CYPRESS_AZURE_AD_B2C_PASSWORD }}
      #     CYPRESS_AZURE_AD_B2C_TENANT_NAME: ${{ secrets.CYPRESS_AZURE_AD_B2C_TENANT_NAME }}

      - name: Link Vercel project
        run: vercel link --yes --token=${{ secrets.VITE_VERCEL_TOKEN }} --project virodip

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VITE_VERCEL_TOKEN }} --confirm
